apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-test
spec: 
  rules: 
  - host: asd.com
    http: 
      paths:
      - path: /
        backend:
          serviceName: gitlab-en
          servicePort: 80
