version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.5.0
#    volumes:
#      - ./config:/usr/share/elasticsearch/config
#      - ./data:/usr/share/elasticsearch/data
#      - ./plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
  kibana: 
    image: kibana:7.5.0
    links: 
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
