apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: es-en
spec: 
  rules: 
  - host: es.keepwork.com
    http: 
      paths:
      - path: /
        backend:
          serviceName: es-en
          servicePort: 9200
