version: '3'

services:
  influxdb:
    image: influxdb
    volumes:
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8089:8089/udp"
      - "8086:8086"
      - "8083:8083"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: iamadmin
